# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'HW_SYN_LAB' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'PusherSwift'
  # Pods for HW_SYN_LAB

  target 'HW_SYN_LABTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HW_SYN_LABUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
